vich_uploader:
    db_driver: orm

    metadata:
        type: attribute

    mappings:
        attachment_file:
            uri_prefix: /attachments
            upload_destination: '%kernel.project_dir%/public/attachments'
            namer: Vich\UploaderBundle\Naming\OrignameNamer
            # namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
